query GetStory($slug: String!) {
  story(slug: $slug) {
    id
    title
    description
    slug {
      full
      short
    }
    publisher {
      login
    }
    dates {
      createdAt
      updatedAt
    }
  }
}
