app:
  name: Twilight's Library
server:
  host: localhost
  port: 2319
  https: true
  wss: true
graphql:
  endpoint: graphql
  subscriptions: graphql/subscriptions

router:
  home: "home"

# DEPRECATED
rewrites: null
