app:
  name: Twilight's Library
client:
  host: localhost
  port: 1339
  https: true
server:
  host: localhost
  port: 2319
  https: true
  wss: true
graphql:
  endpoint: graphql
  subscriptions: graphql/subscriptions

router:
  home: "home"
  rewrites:
    /user/@:login: /@:login
    /story/:slug: /:slug
    /story/:slug/reviews: /:slug/reviews
    /story/:slug/comments: /:slug/comments
    /story/:story/chapter/:chapter: /:story/chapter/:slug

# DEPRECATED
rewrites: null
