#import "api/fragment/story/minimal.gql"
#import "api/fragment/common/dates.gql"

query GetStory($slug: String!) {
  story(slug: $slug) {
    ...storyMinimal

    publisher {
      login
    }

    dates {
      ...commonDates
    }
  }
}
